[tools]
rojo = "rojo-rbx/rojo@7.5.1"
selene = "Kampfkarren/selene@0.28.0"
stylua = 'JohnnyMorganz/StyLua@0.20.0'
wally = 'UpliftGames/wally@0.3.2'
luau-lsp = "JohnnyMorganz/luau-lsp@1.49.1"
lune = "lune-org/lune@0.9.4"
